### ISSUE TITLE
Using evaluate with MASE or RMAE

### ISSUE THREAD

**Issue by concimuscb** [Nixtla/utilsforecast#100]
Both MASE and RMAE require special arguments (seasonality and baseline_models) respectively. As far as I know, there is no way to pass this to evaluate.

**Comment by jmoralez** [comment]
Hey. The example in the [docs](https://nixtlaverse.nixtla.io/utilsforecast/evaluation.html) uses `functools.partial`, but you can also define a regular function, e.g.

```python
from functools import partial

from utilsforecast.losses import mase


def mase12(df, models, train_df, id_col, target_col):
    return mase(
        df=df, models=models, train_df=train_df, id_col=id_col, target_col=target_col, seasonality=12
    )

mase7 = partial(mase, seasonality=7)
```
