### ISSUE TITLE
Give plot_series the option of not showing zeros

### ISSUE THREAD

**Issue by MMenchero** [Nixtla/utilsforecast#118]
### Description

It would be nice to have the option of not plotting zero values when using the `plot_series` function when they're not relevant to the analysis. 

```python
from utilsforecast.data import generate_series
from utilsforecast.plotting import plot_series
ts = generate_series(n_series=1)
ts.loc[30:50, 'y'] = 0
plot_series(ts)
```

We could have an optional parameter, for example `exclude_zeros=True`, that allows users to choose whether to plot zero values.

### Use case

I'm currently working on the Python version of fpp4, specifically [chapter 12.5](https://otexts.com/fpp3/bootstrap.html), which involves plotting the number of calls to a bank, with no calls outside of operational hours.

**Comment by jmoralez** [comment]
The book uses `fill_gaps` which creates `NaN`s for times that were missing. `plot_series` behaves the same way, i.e.

```python
import pandas as pd
from utilsforecast.preprocessing import fill_gaps

bank_calls = pd.read_csv(
    'https://nixtla-public.s3.amazonaws.com/fpp4-datasets/bank_calls.csv',
    parse_dates=['ds']
)
filled = fill_gaps(bank_calls, freq='5min', start='per_serie', end='per_serie')
plot_series(filled)
```
![image](https://github.com/user-attachments/assets/f1013f38-e172-4755-b455-62c97683b2ee)

**Comment by jmoralez** [comment]
Closing due to lack of response.
