### ISSUE TITLE
Polars deprecation warning `is_numeric`

### ISSUE THREAD

**Issue by BCxP-Tobias** [Nixtla/utilsforecast#55]
In the current version 0.0.24 a deprecation warning from polars is thrown regarding the usage of "is_numeric".

Console output:
```
/site-packages/utilsforecast/validation.py:124: DeprecationWarning: `is_numeric` is deprecated. Use `Series.dtype.is_numeric()` instead.
    is_numeric = target.is_numeric()
```

**Comment by jmoralez** [comment]
Hey @BCxP-Tobias, thanks for the report. Are you interested in submitting a PR fixing this? I think we can do the same as here https://github.com/Nixtla/utilsforecast/blob/912e3852ce63bc929044046748c0499398a822dc/utilsforecast/processing.py#L409-L412
