### ISSUE TITLE
plotting.py : _filter_series doesn't handle model names that break regex naming convention (eg. names that contain round parenthesis)

### ISSUE THREAD

**Issue by paksas** [Nixtla/utilsforecast#67]
### Problem: 
Calling `StatsForecast.plot(returns, forecasts, unique_ids = ['AAPL'], models = ['GARCH(2,1)'], level=[80])` yields a KeyError:
`'GARCH(2,1)-lo-80'`

### Steps to reproduce:
Follow the steps outlined in tutorial [https://nixtlaverse.nixtla.io/statsforecast/docs/tutorials/garch_tutorial.html](https://nixtlaverse.nixtla.io/statsforecast/docs/tutorials/garch_tutorial.html) until and including section _Forecast volatility_.  It contains the call shown above.

### Analysis:
The exception originates in the auto-generated file `utilsforecast/plotting.py`.
`forecasts_df` passed as an argument to `plot_series` and filtered using `_filter_series` function has the level columns removed if the model name contains any regex-reserved characters (such as parentheses). 

The code that incorrectly removes those columns is located in line 30 of `plotting.py`:

```
interval_cols = [
      c
      for c in df.columns
      if re.search(rf"^({'|'.join(models)})-(?:lo|hi)-\d+", c)
  ]
 ```

**Comment by jmoralez** [comment]
Thanks for the great report! The fix will be on the next release.

**Comment by paksas** [comment]
thank you so much for a speedy fix :)
