### ISSUE TITLE
processing.counts_by_id returns a zero count for NaNs

### ISSUE THREAD

**Issue by zecevicp** [Nixtla/utilsforecast#91]
In the case where there are no NaNs in the data, the method processing.counts_by_id returns an extra row with the index value NaN and count 0. That makes the subsequent call from _StatsForecast.prepare_fit and utilsforecast.process_df to create a GroupedArray with an empty group, which finally makes the fitting process to fail.

The problem is easily fixable by replacing the line 72:
`return id_counts`
with
`return id_counts[id_counts['counts'] > 0]`

**Comment by jmoralez** [comment]
Hey. Can you provide a reproducible example? The following works as expected on pandas 2.2.2.

```python
import pandas as pd
from utilsforecast.processing import counts_by_id

df = pd.DataFrame({'id': ['a', 'a', 'b']})
counts_by_id(df, id_col='id')
#   id  counts
# 0  a       2
# 1  b       1
```

**Comment by zecevicp** [comment]
Hi, sorry about the delay, I was on vacation.

I've narrowed the problem down to the "Int64" type. The following snippet reproduces the problem:

```
from utilsforecast import processing
import pandas as pd
bad_data = pd.DataFrame({'unique_id': [1, 1, 1], 'col2': [0.0, 0.0, 0.0]})
bad_data['unique_id'] = bad_data['unique_id'].astype("Int64")
processing.counts_by_id(bad_data, id_col='unique_id')
#   unique_id counts
# 0         1      3
# 1      <NA>      0
```

**Comment by jmoralez** [comment]
Which version of pandas are you using? I get the following on 2.2.2:

```python
#    unique_id  counts
# 0          1       3
```

**Comment by zecevicp** [comment]
I'm using 2.1.4

**Comment by jmoralez** [comment]
Thanks! I can reproduce the issue on that version. We had `dropna=False` in the `value_counts` call because it was a bit faster, but I'll set it to `True` to fix this.
